name: FRONTEND_BUILD

on:
  push:
    branches:
       - dev
    paths:
      - 'frontend/**'

jobs:
  code-lint:
    runs-on: ubuntu-latest
    steps:
      # 1. Check out your repository code
      - name: Checkout/Clone the code
        uses: actions/checkout@v7
     
      # 2. Install the NodeJS with a specific version
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Specify your project's Node version
          cache: 'npm'       # Caches npm dependencies automatically

      - name: Install dependencies
        run: npm ci          # Clean install ensuring exact package-lock versions

      - name: Run lint script
        run: npm run lint    # Executes the lint command from package.json


  build-and-push:
    needs: [code-lint]
    runs-on: ubuntu-latest
    steps:
        # 1. Check out your repository code
      - name: Checkout/Clone the code
        uses: actions/checkout@v7

      - name: Login to Docker Hub
        uses: docker/login-action@v4
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # - name: Set up QEMU
      #   uses: docker/setup-qemu-action@v4

      # - name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v4

      - name: Docker Build and push
        uses: docker/build-push-action@v7
        with:
          # Sets the context scope specifically to the frontend directory
          context: ./frontend
          # Points to the Dockerfile inside your frontend folder
          file: ./frontend/Dockerfile
          push: true
          tags: ${{ vars.DOCKERHUB_USERNAME }}/devboard-fe-master:latest

       
       
       
       
       
       
      #   # 2. Install and set up the Python environment
      # - name: Set up Python
      #   uses: actions/setup-python@v5
      #   with:
      #     python-version: '3.14' # Specify your desired version

      #   # 3. This step will install the linting tool
      # - name: Install Linter
      #   run: pip install ruff
      
      #   # 4. This step will run the linter
      # - name: Check the files for linting
      #   run: ruff check .